package Main;

public enum ConsultasExternas {
    NO_ASIGNADO,
    ENFERMERIA,
    APARATO_DIGESTIVO,
    CARDIOLOGIA,
    CIRUGIA_GENERAL,
    DERMATOLOGIA,
    MEDICINA_INTERNA,
    ONCOLOGIA,
    OFTALMOLOGIA,
    PSIQUIATRIA,
    TRAUMATOLOGIA,
    MEDICINA_GENERAL,
}
